# 🧹 Day 3: Pandas Data Cleaning
📅 Date: 11 Oct 2026

## 🎯 Goals for Today
- Handle missing values
- Remove duplicates
- Rename columns
- Change data types
- Apply transformations

In [2]:
## ⚙️ Step 1: Import Pandas & Read  Titanic  Data From Datasets
import pandas as pd
df=pd.read_csv(r'C:\Users\ASHISH RAJ\Desktop\ai-journey\datasets\Titanic-Dataset.csv')
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Handle Missing Values

In [4]:
print(df.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
# Option 1: Drop rows with any missing values
df_droped=df.dropna()
df_droped.shape

(183, 12)

In [8]:
# Option 2: Fill missing age through mean value
df_filled=df.fillna({'Age':df['Age'].mean()})
df_filled.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [17]:
df_filled['Age'].isnull().sum()

np.int64(0)

In [9]:
# Check current data types
df['Age'].dtype

dtype('float64')

In [19]:
df_filled["Age"] = df_filled["Age"].astype("int")

In [22]:
# Check for duplicate rows
df.duplicated().sum()

np.int64(0)

In [24]:
# Standardize the 'Sex' column
df['Sex']=df['Sex'].str.lower().str.strip()
df['Sex'].head(5)

0      male
1    female
2    female
3    female
4      male
Name: Sex, dtype: str

In [26]:

# Calculate IQR for 'Fare'
Q1=df['Fare'].quantile(0.25)
Q3=df['Fare'].quantile(0.75)
IQR=Q3-Q1
IQR

np.float64(23.0896)

In [27]:
# Define bounds
lower_bound=Q1-1.5*IQR
upper_bound=Q3+1.5*IQR

In [29]:
# Filter out outliers
df_clean=df[(df['Fare']>=lower_bound)&(df['Fare']<=upper_bound)]
df_clean

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q